name: Build and commit static pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate static pages
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: npm ci
    - run: node generators/main.js

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - id: deploy-pages
        uses: actions/deploy-pages@v4
